kind: Service
apiVersion: v1
metadata:
  name: svc-products-service
spec:
  type: NodePort
  selector:
    app: svc-products
  ports:
    - name: svc-products-service
      protocol: TCP
      port: 80
      targetPort: 3333
