apiVersion: apps/v1
kind: Deployment
metadata:
  name: svc-user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: svc-user
  template:
    metadata:
      labels:
        app: svc-user
    spec:
      containers:
        - name: svc-user
          image: svc-user:latests
          imagePullPolicy: Always
          ports:
            - containerPort: 3333
