kind: Service
apiVersion: v1
metadata:
  name: svc-user-service
spec:
  type: NodePort
  selector:
    app: svc-user
  ports:
    - name: svc-user-service
      protocol: TCP
      port: 80
      targetPort: 3333
