name: ci
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
        package_manager:
          - yarn
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: git fetch origin master
      - run: yarn install
      - name: build svc-cart
        shell: bash
        run: yarn nx build svc-cart
      - name: build docker svc-cart
        shell: bash      
        run: docker build -f ./apps/svc-cart/Dockerfile . -t svc-cart
#       - name: Deploy to Netlify
#         shell: bash
#         if: github.ref == 'refs/heads/master'
#         run: NETLIFY_TOKEN=tHInavUB4ywYxyyFWCxUd0N0OvBLJ5xCoSFjtxTZ310 yarn affected:deploy --base=master~1 --head=master
