name: ci
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
        package_manager:
          - yarn
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: git fetch origin master
      - run: yarn install
      - name: build services
        shell: bash
        run: |
              yarn nx build svc-cart
              yarn nx build svc-products
              yarn nx build svc-user



      - name: Get commit short hash and branch name
        id: vars
        shell: bash
        run: |
          echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

#      - name: build docker
#        shell: bash
#        run: |
#              docker build -f ./apps/svc-cart/Dockerfile . -t ruslanbyondxr/svc-cart:${{ steps.vars.outputs.sha_short }}
#              docker build -f ./apps/svc-products/Dockerfile . -t ruslanbyondxr/svc-products:${{ steps.vars.outputs.sha_short }}
#              docker build -f ./apps/svc-user/Dockerfile . -t ruslanbyondxr/svc-user:${{ steps.vars.outputs.sha_short }}

#      - name: push to docker hub
#        shell: bash
#        run: |
#              docker push ruslanbyondxr/svc-cart:${{ steps.vars.outputs.sha_short }}
#              docker push ruslanbyondxr/svc-products:${{ steps.vars.outputs.sha_short }}
#              docker push ruslanbyondxr/svc-user:${{ steps.vars.outputs.sha_short }}

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./apps/svc-cart
          push: true
          tags: ruslanbyondxr/svc-cart:${{ steps.vars.outputs.sha_short }}
